cargo-features = ["default-run"]

[package]
name = "git-together"
version = "0.1.0-alpha.17"
authors = ["Alpha Chen <alpha.chen@gmail.com>"]
edition = "2018"
default-run = "git-together"

[dependencies]
failure = "0.1"
git2 = "0.7"
